// Site Control Plane - DCCP
// Copyright 2026 Summon Software Labs.
// SPDX-License-Identifier: Apache-2.0

#include <algorithm>
#include <cstdint>
#include <limits>
#include <string>
#include <vector>

#include "scp/composition.hpp"
#include "scp/digest.hpp"
#include "scp/evidence.hpp"
#include "scp/ids.hpp"
#include "scp/policy.hpp"
#include "scp/readiness.hpp"
#include "scp/site_state.hpp"
#include "scp/status.hpp"
#include "scp/text.hpp"
#include "scp/time.hpp"
#include "test_support.hpp"

/// \file test_property_composition.cpp
/// Seeded randomized properties of the composition engine.
///
/// Every scenario is generated by a splitmix64 generator from an explicit
/// constant, so any failure reproduces exactly: the seed and the full evidence
/// set are printed when a check fails. Nothing here reads a clock, the system
/// random device or an environment variable.

namespace {

using scp::EvidenceKind;
using scp::EvidenceRecord;
using scp::Result;
using scp::SiteStateSnapshot;
using scp::SlotResolution;
using scp::SourceAuthority;
using scp::Timestamp;

constexpr std::uint64_t kMasterSeed = 0x5C9E5EED0F0D1CE5ULL;
constexpr std::uint64_t kSeedStride = 0x9E3779B97F4A7C15ULL;
constexpr std::uint64_t kScenarioCount = 240;

/// Deterministic 64-bit generator (splitmix64). No std::random_device, no
/// wall-clock seeding, no std::rand.
class SplitMix64 {
 public:
  explicit SplitMix64(std::uint64_t seed) noexcept : state_(seed) {}

  std::uint64_t next() noexcept {
    state_ += 0x9E3779B97F4A7C15ULL;
    std::uint64_t value = state_;
    value = (value ^ (value >> 30U)) * 0xBF58476D1CE4E5B9ULL;
    value = (value ^ (value >> 27U)) * 0x94D049BB133111EBULL;
    return value ^ (value >> 31U);
  }

  std::uint64_t below(std::uint64_t bound) noexcept {
    return bound == 0 ? 0 : next() % bound;
  }

  bool coin() noexcept { return (next() & 1ULL) != 0ULL; }

 private:
  std::uint64_t state_;
};

std::string describe(const EvidenceRecord& record) {
  std::string text = std::string(scp::to_string(record.provenance.authority)) + "/" +
                     std::string(scp::to_string(record.kind)) +
                     " schema=" + std::to_string(record.schema_version) +
                     " epoch=" + std::to_string(record.provenance.epoch.value()) +
                     " generation=" + std::to_string(record.provenance.generation.value()) +
                     " sequence=" + std::to_string(record.provenance.sequence.value()) +
                     " instance=" + record.provenance.instance.to_hex() +
                     " issued=" + std::to_string(record.provenance.issued_at.nanos) +
                     " valid_until=" + std::to_string(record.provenance.valid_until.nanos) +
                     " origin=" + std::string(scp::to_string(record.origin)) +
                     " body=" + std::to_string(record.body.size()) + "B" +
                     " id=" + record.id.to_hex();
  return text;
}

/// Records a check; on failure it prints the seed and the whole evidence set, so
/// the case is reproducible from the printed output alone.
void check_scenario(bool condition, const char* expression, const std::string& context,
                    std::uint64_t seed, const std::vector<EvidenceRecord>& records) {
  if (condition) {
    scp_test::Context::instance().check(true, expression, __FILE__, __LINE__);
    return;
  }
  scp_test::Context::instance().note("seed=" + std::to_string(seed) + " (" +
                                     std::to_string(seed) + "ULL) " + context);
  scp_test::Context::instance().note("scenario carries " + std::to_string(records.size()) +
                                     " record(s):");
  for (const EvidenceRecord& record : records) {
    scp_test::Context::instance().note("  " + describe(record));
  }
  scp_test::Context::instance().check(false, expression, __FILE__, __LINE__);
}

/// Records a check with a one-line failure report. The scenario is still fully
/// reproducible from the printed seed because the generator is deterministic.
void check_scenario_brief(bool condition, const char* expression, const std::string& brief,
                          std::uint64_t seed) {
  if (condition) {
    scp_test::Context::instance().check(true, expression, __FILE__, __LINE__);
    return;
  }
  scp_test::Context::instance().note("seed=" + std::to_string(seed) + " " + brief);
  scp_test::Context::instance().check(false, expression, __FILE__, __LINE__);
}

/// Names every pair of publications that tie at one (authority, kind, epoch,
/// generation, sequence). Such a pair is what makes an arrival-ordered tie
/// resolution observable, so it is the first thing a failure report needs.
std::string describe_tied_keys(const std::vector<EvidenceRecord>& records) {
  std::string text;
  for (std::size_t first = 0; first < records.size(); ++first) {
    for (std::size_t second = first + 1; second < records.size(); ++second) {
      const EvidenceRecord& left = records[first];
      const EvidenceRecord& right = records[second];
      if (!(scp::slot_of(left) == scp::slot_of(right))) {
        continue;
      }
      if (!(left.provenance.epoch == right.provenance.epoch) ||
          !(left.provenance.generation == right.provenance.generation) ||
          !(left.provenance.sequence == right.provenance.sequence)) {
        continue;
      }
      text += " [" + std::string(scp::to_string(left.kind)) +
              " epoch=" + std::to_string(left.provenance.epoch.value()) +
              " generation=" + std::to_string(left.provenance.generation.value()) +
              " sequence=" + std::to_string(left.provenance.sequence.value()) +
              " ids=" + left.id.to_hex() + "/" + right.id.to_hex() +
              " distinct_instance=" + (left.provenance.instance == right.provenance.instance ? "no" : "yes") +
              " distinct_digest=" +
              (left.provenance.body_digest == right.provenance.body_digest ? "no" : "yes") + "]";
    }
  }
  return text.empty() ? std::string(" none") : text;
}

void append(std::vector<EvidenceRecord>& into, const std::vector<EvidenceRecord>& extra) {
  into.insert(into.end(), extra.begin(), extra.end());
}

scp::CompositionOptions options_for(Timestamp evaluation_time, const scp::SitePolicy& policy,
                                    std::uint64_t site_generation = 1) {
  scp::CompositionOptions options;
  options.site = scp_test::default_site();
  options.site_generation = scp::SiteGeneration(site_generation);
  options.evaluation_time = evaluation_time;
  options.policy = policy;
  return options;
}

// ---------------------------------------------------------------------------
// Scenario generation
// ---------------------------------------------------------------------------

constexpr std::int64_t kIssuedOffsets[] = {-4000, -1000, -100, 0, 0, 0, 100, 5000};

std::uint32_t small_percent(SplitMix64& rng) {
  return static_cast<std::uint32_t>(rng.below(101));
}

scp::ReadinessLevel random_readiness(SplitMix64& rng) {
  return static_cast<scp::ReadinessLevel>(rng.below(5));
}

scp::Severity random_severity(SplitMix64& rng) {
  return static_cast<scp::Severity>(rng.below(5));
}

scp::EvidenceBody random_body(EvidenceKind kind, std::uint64_t generation, SplitMix64& rng) {
  switch (kind) {
    case EvidenceKind::FacilityState: {
      scp::FacilityStateEvidence body;
      body.generation = scp::FacilityStateGeneration(generation);
      body.worst_active_severity = random_severity(rng);
      body.active_incidents = static_cast<std::uint32_t>(rng.below(4));
      body.degraded_operation = rng.coin();
      body.emergency_declared = rng.below(8) == 0;
      return body;
    }
    case EvidenceKind::Lifecycle: {
      scp::LifecycleEvidence body;
      body.state = static_cast<scp::LifecycleState>(1 + rng.below(8));
      body.entered_at = scp_test::instant_after(-100);
      body.transition_in_progress = rng.coin();
      return body;
    }
    case EvidenceKind::Capacity: {
      scp::CapacityEvidence body;
      body.snapshot = scp::SnapshotId(0xC0FFEE0000000001ULL, rng.next());
      body.generation = scp::CapacityGeneration(generation);
      body.total_units = rng.below(3) == 0 ? 0 : 100;
      body.committed_units = rng.below(101);
      body.available_units = rng.below(101);
      body.oversubscribed = rng.below(8) == 0;
      return body;
    }
    case EvidenceKind::PowerReadiness:
    case EvidenceKind::CoolingReadiness: {
      scp::ReadinessEvidence body;
      body.snapshot = scp::SnapshotId(0xC0FFEE0000000002ULL, rng.next());
      body.readiness = random_readiness(rng);
      body.headroom_milli_kw = rng.below(10000000);
      body.available_domains = static_cast<std::uint32_t>(rng.below(4));
      body.required_domains = static_cast<std::uint32_t>(rng.below(4));
      return body;
    }
    case EvidenceKind::Policy: {
      scp::PolicyEvidence body;
      body.generation = scp::PolicyGeneration(generation);
      body.rule_count = static_cast<std::uint32_t>(rng.below(8));
      return body;
    }
    case EvidenceKind::Incident: {
      scp::IncidentEvidence body;
      body.active_incidents = static_cast<std::uint32_t>(rng.below(4));
      body.worst_active_severity = random_severity(rng);
      body.emergency_declared = rng.below(8) == 0;
      body.earliest_active = scp_test::instant_after(-100);
      body.suppressed_incidents = static_cast<std::uint32_t>(rng.below(3));
      return body;
    }
    case EvidenceKind::Maintenance: {
      scp::MaintenanceEvidence body;
      body.mode = static_cast<scp::MaintenanceMode>(rng.below(4));
      body.active_windows = static_cast<std::uint32_t>(rng.below(3));
      body.scheduled_windows = static_cast<std::uint32_t>(rng.below(3));
      body.next_window_start = scp_test::instant_after(600);
      body.drain_in_progress = rng.coin();
      body.drained_percent = small_percent(rng);
      return body;
    }
    case EvidenceKind::AsiCapability:
    case EvidenceKind::DfiCapability: {
      scp::CapabilityEvidence body;
      body.readiness = random_readiness(rng);
      const std::uint32_t total = static_cast<std::uint32_t>(rng.below(5));
      body.total_domains = total;
      body.ready_domains = static_cast<std::uint32_t>(rng.below(static_cast<std::uint64_t>(total) + 1ULL));
      body.ready_units = rng.below(1024);
      return body;
    }
    case EvidenceKind::ServiceClass: {
      constexpr std::string_view kClassNames[] = {"interactive-inference", "batch-queue",
                                                  "control-plane"};
      scp::ServiceClassEvidence body;
      const std::uint64_t count = rng.below(3);
      body.class_count = static_cast<std::uint32_t>(count);
      for (std::uint64_t index = 0; index < count; ++index) {
        const std::string_view name_text = kClassNames[rng.below(3)];
        const Result<scp::Name> parsed = scp::Name::parse(name_text);
        if (!parsed.has_value()) {
          continue;
        }
        scp::ServiceClassObligation obligation;
        obligation.service_class = parsed.value();
        obligation.protected_class = rng.coin();
        obligation.minimum_ready_units = static_cast<std::uint32_t>(rng.below(64));
        obligation.minimum_readiness_percent = small_percent(rng);
        body.obligations.push_back(obligation);
      }
      return body;
    }
  }
  return scp::FacilityStateEvidence{};
}

Result<EvidenceRecord> random_record(EvidenceKind kind, std::uint64_t epoch,
                                     std::uint64_t generation, std::uint64_t sequence,
                                     std::uint64_t instance, Timestamp issued_at,
                                     Timestamp valid_until, scp::EvidenceOrigin origin,
                                     SplitMix64& rng) {
  scp::Provenance provenance;
  provenance.authority = scp::owner_of(kind);
  provenance.instance = scp_test::instance_for(instance);
  provenance.epoch = scp::Epoch(epoch);
  provenance.generation = scp::SourceGeneration(generation);
  provenance.sequence = scp::Sequence(sequence);
  provenance.issued_at = issued_at;
  provenance.valid_until = valid_until;
  Result<EvidenceRecord> record =
      EvidenceRecord::create(provenance, kind, random_body(kind, generation, rng));
  if (!record.has_value()) {
    return record.status();
  }
  record.value().origin = origin;
  return record;
}

std::vector<EvidenceRecord> random_evidence_set(SplitMix64& rng, Timestamp evaluation) {
  (void)evaluation;
  std::vector<EvidenceRecord> records;
  for (std::uint16_t raw = 1; raw <= static_cast<std::uint16_t>(scp::kEvidenceKindCount); ++raw) {
    const EvidenceKind kind = static_cast<EvidenceKind>(raw);
    const std::uint64_t count = rng.below(4);
    for (std::uint64_t index = 0; index < count; ++index) {
      const std::uint64_t epoch = 1 + rng.below(3);
      const std::uint64_t generation = 1 + rng.below(4);
      const std::uint64_t sequence = 1 + rng.below(3);
      const std::uint64_t instance = 1 + rng.below(4);
      const std::size_t offset_index =
          static_cast<std::size_t>(rng.below(sizeof(kIssuedOffsets) / sizeof(kIssuedOffsets[0])));
      const Timestamp issued_at = scp_test::instant_after(kIssuedOffsets[offset_index]);
      Timestamp valid_until{};
      const std::uint64_t expiry = rng.below(5);
      if (expiry == 1) {
        valid_until = scp_test::instant_after(-10);
      } else if (expiry == 2) {
        valid_until = scp_test::instant_after(600);
      }
      scp::EvidenceOrigin origin = scp::EvidenceOrigin::Ingested;
      if (rng.below(4) == 0) {
        origin = scp::EvidenceOrigin::RecoveredFromJournal;
      } else if (rng.below(4) == 0) {
        origin = scp::EvidenceOrigin::Revalidated;
      }
      const Result<EvidenceRecord> record = random_record(kind, epoch, generation, sequence,
                                                          instance, issued_at, valid_until, origin,
                                                          rng);
      if (record.has_value()) {
        records.push_back(record.value());
      }
    }
  }
  return records;
}

std::vector<EvidenceRecord> shuffled_records(const std::vector<EvidenceRecord>& records,
                                             SplitMix64& rng) {
  std::vector<EvidenceRecord> shuffled = records;
  if (shuffled.size() > 1) {
    for (std::size_t index = shuffled.size() - 1; index > 0; --index) {
      const std::size_t other = static_cast<std::size_t>(
          rng.below(static_cast<std::uint64_t>(index) + 1ULL));
      std::swap(shuffled[index], shuffled[other]);
    }
  }
  return shuffled;
}

constexpr std::string_view kRuleIds[] = {"rule-a", "rule-b", "rule-c"};
constexpr std::string_view kMetrics[] = {
    scp::kMetricCapacityHeadroomPercent, scp::kMetricAvailableCapacityUnits,
    scp::kMetricPowerHeadroomMilliKw,    scp::kMetricCoolingHeadroomMilliKw,
    scp::kMetricPowerRedundancyAvailable, scp::kMetricCoolingRedundancyAvailable,
    scp::kMetricReadinessPercent,        scp::kMetricAsiReadinessPercent,
    scp::kMetricDfiReadinessPercent,     scp::kMetricActiveIncidents,
    scp::kMetricActiveMaintenanceWindows, scp::kMetricDrainedPercent};

scp::SitePolicy random_policy(SplitMix64& rng, std::size_t rule_count) {
  scp::SitePolicy policy = scp_test::strict_policy();
  policy.generation = scp::PolicyGeneration(1 + rng.below(4));
  policy.freshness.stale_after = scp::seconds(static_cast<std::int64_t>(rng.below(2000)));
  const std::int64_t stale_seconds = policy.freshness.stale_after.nanos / scp::kNanosPerSecond;
  policy.freshness.expire_after =
      scp::seconds(stale_seconds + static_cast<std::int64_t>(rng.below(4000)));
  policy.capacity_headroom_constrained_percent = small_percent(rng);
  policy.capacity_headroom_degraded_percent =
      static_cast<std::uint32_t>(rng.below(static_cast<std::uint64_t>(
                                     policy.capacity_headroom_constrained_percent) +
                                 1ULL));
  policy.domain_readiness_degraded_percent = small_percent(rng);
  policy.domain_readiness_unavailable_percent = static_cast<std::uint32_t>(
      rng.below(static_cast<std::uint64_t>(policy.domain_readiness_degraded_percent) + 1ULL));
  policy.required_redundancy_domains = static_cast<std::uint32_t>(rng.below(3));
  policy.maintenance_minimum_readiness_percent = small_percent(rng);
  policy.recovery_minimum_drained_percent = small_percent(rng);
  policy.return_to_service_minimum_readiness_percent = small_percent(rng);
  policy.max_constraints = static_cast<std::size_t>(1 + rng.below(24));
  policy.require_complete_evidence_for_new_obligations = rng.coin();
  policy.require_fresh_evidence_for_new_obligations = rng.coin();
  policy.require_unconflicted_evidence_for_new_obligations = rng.coin();
  for (std::size_t index = 0; index < rule_count; ++index) {
    scp::ThresholdRule rule;
    const Result<scp::Name> rule_id = scp::Name::parse(kRuleIds[rng.below(3)]);
    if (!rule_id.has_value()) {
      continue;
    }
    rule.rule_id = rule_id.value();
    rule.kind = scp::ConstraintKind::CapacityHeadroomLow;
    rule.severity = random_severity(rng);
    rule.comparison = static_cast<scp::Comparison>(1 + rng.below(4));
    rule.threshold = rng.below(101);
    rule.blocking = rng.coin();
    rule.subject = std::string(kMetrics[rng.below(sizeof(kMetrics) / sizeof(kMetrics[0]))]);
    policy.rules.push_back(rule);
  }
  return policy;
}

// ---------------------------------------------------------------------------
// Hostile input
// ---------------------------------------------------------------------------

std::uint64_t pick_extreme(SplitMix64& rng, std::uint64_t normal) {
  switch (rng.below(6)) {
    case 0: return 0;
    case 1: return std::numeric_limits<std::uint64_t>::max();
    case 2: return 1;
    case 3: return rng.next();
    default: return normal;
  }
}

std::int64_t pick_extreme_time(SplitMix64& rng) {
  switch (rng.below(6)) {
    case 0: return 0;
    case 1: return std::numeric_limits<std::int64_t>::min();
    case 2: return std::numeric_limits<std::int64_t>::max();
    case 3: return 1;
    case 4: return -1;
    default: return static_cast<std::int64_t>(rng.next() >> 1U);
  }
}

void rederive(EvidenceRecord& record) {
  record.provenance.body_digest = scp::Digest::of(
      std::span<const std::uint8_t>(record.body.data(), record.body.size()));
  const Result<scp::EvidenceId> identity = scp::derive_evidence_id(
      record.provenance, record.kind, record.schema_version, record.body);
  if (identity.has_value()) {
    record.id = identity.value();
  }
}

void corrupt_records(std::vector<EvidenceRecord>& records, SplitMix64& rng) {
  for (EvidenceRecord& record : records) {
    const std::uint64_t mutations = 1 + rng.below(3);
    for (std::uint64_t mutation = 0; mutation < mutations; ++mutation) {
      switch (rng.below(10)) {
        case 0:
          if (!record.body.empty()) {
            record.body[static_cast<std::size_t>(rng.below(record.body.size()))] ^= 0xFFU;
          }
          break;
        case 1:
          if (!record.body.empty()) {
            record.body[static_cast<std::size_t>(rng.below(record.body.size()))] ^= 0x01U;
            rederive(record);
          }
          break;
        case 2:
          switch (rng.below(5)) {
            case 0: record.schema_version = 0; break;
            case 1: record.schema_version = 2; break;
            case 2: record.schema_version = 999; break;
            case 3: record.schema_version = std::numeric_limits<std::uint16_t>::max(); break;
            default: break;
          }
          break;
        case 3:
          record.provenance.generation = scp::SourceGeneration(
              pick_extreme(rng, record.provenance.generation.value()));
          break;
        case 4:
          record.provenance.sequence = scp::Sequence(
              pick_extreme(rng, record.provenance.sequence.value()));
          break;
        case 5:
          record.provenance.epoch = scp::Epoch(pick_extreme(rng, record.provenance.epoch.value()));
          break;
        case 6:
          record.provenance.issued_at = Timestamp{pick_extreme_time(rng)};
          break;
        case 7:
          record.provenance.valid_until = Timestamp{pick_extreme_time(rng)};
          break;
        case 8:
          if (rng.below(4) == 0) {
            record.id = scp::EvidenceId{};
          } else {
            record.id = scp::EvidenceId(rng.next(), rng.next());
          }
          break;
        default:
          if (rng.coin()) {
            record.provenance.body_digest = scp::Digest{};
          } else {
            record.provenance.instance = scp::SourceInstanceId{};
          }
          break;
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Reduction accounting
// ---------------------------------------------------------------------------

std::size_t distinct_id_count(const std::vector<EvidenceRecord>& records) {
  std::vector<scp::EvidenceId> ids;
  ids.reserve(records.size());
  for (const EvidenceRecord& record : records) {
    ids.push_back(record.id);
  }
  std::sort(ids.begin(), ids.end());
  ids.erase(std::unique(ids.begin(), ids.end()), ids.end());
  return ids.size();
}

std::size_t distinct_rejected_count(const scp::ReductionResult& reduction) {
  std::vector<scp::EvidenceId> ids;
  ids.reserve(reduction.rejected.size());
  for (const EvidenceRecord& record : reduction.rejected) {
    ids.push_back(record.id);
  }
  std::sort(ids.begin(), ids.end());
  ids.erase(std::unique(ids.begin(), ids.end()), ids.end());
  return ids.size();
}

std::size_t slot_superseded_count(const scp::ReductionResult& reduction) {
  std::size_t total = 0;
  for (const SlotResolution& resolution : reduction.slots) {
    total += resolution.superseded.size();
  }
  return total;
}

std::size_t slot_conflicting_count(const scp::ReductionResult& reduction) {
  std::size_t total = 0;
  for (const SlotResolution& resolution : reduction.slots) {
    total += resolution.conflicting.size();
  }
  return total;
}

/// Identity of every record the five reporting buckets hold.
std::vector<scp::EvidenceId> bucket_ids(const scp::ReductionResult& reduction) {
  std::vector<scp::EvidenceId> ids;
  ids.reserve(reduction.accepted.size() + reduction.superseded.size() +
              reduction.conflicting.size() + reduction.redundant.size() +
              reduction.rejected.size());
  const std::vector<const std::vector<EvidenceRecord>*> buckets = {
      &reduction.accepted, &reduction.superseded, &reduction.conflicting, &reduction.redundant,
      &reduction.rejected};
  for (const std::vector<EvidenceRecord>* bucket : buckets) {
    for (const EvidenceRecord& record : *bucket) {
      ids.push_back(record.id);
    }
  }
  return ids;
}

std::size_t repeated_id_count(std::vector<scp::EvidenceId> ids) {
  std::sort(ids.begin(), ids.end());
  std::size_t repeats = 0;
  for (std::size_t index = 1; index < ids.size(); ++index) {
    if (ids[index] == ids[index - 1]) {
      ++repeats;
    }
  }
  return repeats;
}

/// The accounting identity the reduction's reported buckets must satisfy
/// (include/scp/composition.hpp:47-83): every distinct identity in the batch
/// lands in exactly one of accepted, superseded, conflicting, redundant or
/// rejected, and a record that repeats an identity already present is counted in
/// duplicates_merged instead.
void check_reduction_partition(const std::vector<EvidenceRecord>& records,
                               const scp::ReductionResult& reduction, std::uint64_t seed) {
  const std::size_t input = distinct_id_count(records);
  const std::size_t reported = reduction.accounted();
  const std::vector<scp::EvidenceId> ids = bucket_ids(reduction);
  const std::size_t repeats = repeated_id_count(ids);
  const std::string buckets =
      "accepted=" + std::to_string(reduction.accepted.size()) +
      " superseded=" + std::to_string(reduction.superseded.size()) +
      " conflicting=" + std::to_string(reduction.conflicting.size()) +
      " redundant=" + std::to_string(reduction.redundant.size()) +
      " rejected=" + std::to_string(reduction.rejected.size()) +
      " accounted=" + std::to_string(reported) +
      " distinct_input=" + std::to_string(input) +
      " duplicates_merged=" + std::to_string(reduction.duplicates_merged) +
      " identities_in_more_than_one_bucket=" + std::to_string(repeats) +
      " slot_reported_superseded=" + std::to_string(slot_superseded_count(reduction)) +
      " slot_reported_conflicting=" + std::to_string(slot_conflicting_count(reduction));
  check_scenario(reported == input,
                 "the reported reduction buckets account for every distinct input identity",
                 buckets, seed, records);
  check_scenario(repeats == 0,
                 "no identity is reported in more than one reduction bucket", buckets, seed,
                 records);
}

}  // namespace

SCP_TEST(order_independence_over_random_evidence_sets) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  std::size_t compared = 0;
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed + scenario * kSeedStride;
    SplitMix64 rng(seed);
    const std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const Result<SiteStateSnapshot> reference =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (!reference.has_value()) {
      check_scenario(false, "the reference composition succeeds", "compose reported " +
                       reference.status().to_string(), seed, records);
      continue;
    }
    bool reported = false;
    for (int permutation = 0; permutation < 5; ++permutation) {
      const std::vector<EvidenceRecord> permuted = shuffled_records(records, rng);
      const Result<SiteStateSnapshot> candidate =
          scp::compose_site_state(permuted, options_for(evaluation, policy));
      const bool permutation_matches_reference =
          candidate.has_value() &&
          candidate.value().snapshot_digest == reference.value().snapshot_digest;
      if (candidate.has_value()) {
        ++compared;
      }
      if (permutation_matches_reference) {
        SCP_CHECK(permutation_matches_reference);
        continue;
      }
      if (!reported) {
        reported = true;
        scp_test::Context::instance().note(
            "permutations of one evidence set composed to different snapshot digests. A tie at "
            "the greatest (epoch, generation, sequence) must be broken by content-addressed "
            "identity, so that no reported field of a resolution - not the accepted identity, not "
            "the digest, not an explanation string - can depend on which publication arrived "
            "first; tied keys:" +
            describe_tied_keys(records));
        check_scenario(false, "every permutation composes to the reference snapshot digest",
                       "first disagreeing permutation " + std::to_string(permutation), seed, records);
        continue;
      }
      check_scenario_brief(false, "every permutation composes to the reference snapshot digest",
                           "permutation " + std::to_string(permutation) + " also disagreed", seed);
    }
  }
  SCP_CHECK_EQ(compared, static_cast<std::size_t>(kScenarioCount) * 5);
}

SCP_TEST(composition_is_idempotent) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 3ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    const std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const Result<SiteStateSnapshot> first =
        scp::compose_site_state(records, options_for(evaluation, policy));
    const Result<SiteStateSnapshot> second =
        scp::compose_site_state(records, options_for(evaluation, policy));
    const bool same = first.has_value() && second.has_value() &&
                      first.value().snapshot_digest == second.value().snapshot_digest &&
                      first.value().evidence_digest == second.value().evidence_digest;
    check_scenario(same, "composing the same evidence twice gives the same digests",
                   "the second composition differed", seed, records);
  }
}

SCP_TEST(a_newer_generation_never_yields_an_older_accepted_generation) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 5ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    const std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const Result<SiteStateSnapshot> before =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (!before.has_value()) {
      continue;
    }
    const EvidenceKind kind = static_cast<EvidenceKind>(1 + rng.below(scp::kEvidenceKindCount));
    const scp::EvidenceSlot slot{scp::owner_of(kind), kind};
    const SlotResolution* previous = before.value().find_slot(slot);
    const std::uint64_t previous_generation =
        previous == nullptr ? 0ULL : previous->accepted_generation.value();
    // An unresolved slot carries no epoch, and epoch zero is "not set" rather
    // than a statement about the publisher.
    const std::uint64_t previous_epoch =
        (previous == nullptr || previous->accepted_epoch.is_unset()) ? 1ULL
                                                                    : previous->accepted_epoch.value();
    if (previous_generation >= std::numeric_limits<std::uint64_t>::max() - 1ULL) {
      continue;
    }
    const std::uint64_t next_generation = previous_generation + 1ULL;
    const Result<EvidenceRecord> newer = random_record(kind, previous_epoch, next_generation, 1,
                                                       9, evaluation, Timestamp{},
                                                       scp::EvidenceOrigin::Ingested, rng);
    if (!newer.has_value()) {
      continue;
    }
    std::vector<EvidenceRecord> augmented = records;
    augmented.push_back(newer.value());
    const Result<SiteStateSnapshot> after =
        scp::compose_site_state(augmented, options_for(evaluation, policy));
    if (!after.has_value()) {
      check_scenario(false, "adding a newer generation still composes",
                     "compose reported " + after.status().to_string(), seed, augmented);
      continue;
    }
    const SlotResolution* resolution = after.value().find_slot(slot);
    const bool resolved = resolution != nullptr;
    check_scenario(resolved, "the slot is resolved after adding a newer generation",
                   "the slot disappeared", seed, augmented);
    if (!resolved) {
      continue;
    }
    check_scenario(resolution->accepted_generation.value() >= previous_generation,
                   "a strictly newer publication never lowers the accepted generation",
                   "previous=" + std::to_string(previous_generation) + " after=" +
                       std::to_string(resolution->accepted_generation.value()),
                   seed, augmented);
    check_scenario(resolution->accepted_id == newer.value().id,
                   "the newest publication is the accepted one for its slot",
                   "accepted=" + resolution->accepted_id.to_hex() + " expected=" +
                       newer.value().id.to_hex(),
                   seed, augmented);
  }
}

SCP_TEST(duplicating_records_never_changes_the_digest) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  bool first_failure = true;
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 7ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const Result<SiteStateSnapshot> reference =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (!reference.has_value() || records.empty()) {
      continue;
    }
    std::vector<EvidenceRecord> duplicated = records;
    const std::uint64_t copies = 1 + rng.below(5);
    for (std::uint64_t copy = 0; copy < copies; ++copy) {
      const std::size_t index = static_cast<std::size_t>(rng.below(records.size()));
      duplicated.push_back(records[index]);
    }
    const Result<SiteStateSnapshot> after =
        scp::compose_site_state(duplicated, options_for(evaluation, policy));
    const bool same = after.has_value() &&
                      after.value().snapshot_digest == reference.value().snapshot_digest;
    if (same) {
      SCP_CHECK(same);
      continue;
    }
    if (first_failure) {
      first_failure = false;
      scp_test::Context::instance().note(
          "one redundant copy of a record changed the snapshot digest. A duplicate is the same "
          "content-addressed identity, so it must be merged and counted without moving the digest "
          "of the composed picture: the digest describes what the site believes, not how many "
          "copies of a publication arrived.");
      check_scenario(false, "exact duplicates never change the snapshot digest",
                     std::to_string(copies) + " duplicate(s) changed the digest", seed, duplicated);
      continue;
    }
    check_scenario_brief(false, "exact duplicates never change the snapshot digest",
                         std::to_string(copies) + " duplicate(s) changed the digest", seed);
  }
}

SCP_TEST(hostile_input_never_crashes_and_never_fabricates_a_digest) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  std::size_t succeeded = 0;
  std::size_t refused = 0;
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 11ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    if (records.empty()) {
      records.push_back(EvidenceRecord{});
    }
    corrupt_records(records, rng);
    const Result<SiteStateSnapshot> composed =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (!composed.has_value()) {
      ++refused;
      check_scenario(!composed.status().message().empty(),
                     "a refused composition carries a status message", "empty status message",
                     seed, records);
      continue;
    }
    ++succeeded;
    const SiteStateSnapshot& snapshot = composed.value();
    check_scenario(!snapshot.snapshot_digest.is_zero(),
                   "a composed snapshot never carries an unset digest", "zero snapshot digest",
                   seed, records);
    check_scenario(scp::compute_snapshot_digest(snapshot) == snapshot.snapshot_digest,
                   "the composed snapshot digest verifies",
                   "compute_snapshot_digest disagreed", seed, records);
    check_scenario(scp::compute_evidence_digest(snapshot.slots) == snapshot.evidence_digest,
                   "the composed evidence digest verifies",
                   "compute_evidence_digest disagreed", seed, records);
    const Result<SiteStateSnapshot> repeated =
        scp::compose_site_state(records, options_for(evaluation, policy));
    const bool deterministic = repeated.has_value() &&
                               repeated.value().snapshot_digest == snapshot.snapshot_digest;
    check_scenario(deterministic, "hostile input composes deterministically",
                   "a second composition differed", seed, records);
  }
  SCP_CHECK(succeeded > 0);
  SCP_CHECK_EQ(succeeded + refused, static_cast<std::size_t>(kScenarioCount));

  // The other branch of the property: the same hostile bytes under a policy
  // whose constraint bound is too small to describe them. Composition must
  // refuse with a status instead of composing a truncated picture.
  std::size_t tight_refusals = 0;
  scp::SitePolicy tight = scp_test::strict_policy();
  tight.max_constraints = 2;
  for (std::uint64_t scenario = 0; scenario < 32; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 23ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    corrupt_records(records, rng);
    const Result<SiteStateSnapshot> composed =
        scp::compose_site_state(records, options_for(evaluation, tight));
    if (!composed.has_value()) {
      ++tight_refusals;
      check_scenario(composed.status().code() == scp::StatusCode::LimitExceeded,
                     "a refused hostile composition reports why",
                     "compose reported " + composed.status().to_string(), seed, records);
      continue;
    }
    check_scenario(composed.value().constraints.size() <= tight.max_constraints,
                   "a successful composition respects the constraint bound",
                   "constraints=" + std::to_string(composed.value().constraints.size()), seed,
                   records);
  }
  SCP_CHECK(tight_refusals > 0);
}

SCP_TEST(constraints_are_bounded_by_the_policy_and_the_bound_is_reported) {
  const Timestamp evaluation = scp_test::base_instant();
  std::size_t limited = 0;
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 13ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    const std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const scp::SitePolicy policy = random_policy(rng, static_cast<std::size_t>(rng.below(3)));
    SCP_CHECK(policy.validate().ok());
    const Result<SiteStateSnapshot> composed =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (composed.has_value()) {
      check_scenario(composed.value().constraints.size() <= policy.max_constraints,
                     "a snapshot never carries more constraints than the policy allows",
                     "constraints=" + std::to_string(composed.value().constraints.size()) +
                         " max_constraints=" + std::to_string(policy.max_constraints),
                     seed, records);
      continue;
    }
    ++limited;
    check_scenario(composed.status().code() == scp::StatusCode::LimitExceeded,
                   "exceeding the constraint bound is reported as LimitExceeded",
                   "compose reported " + composed.status().to_string(), seed, records);
  }
  SCP_CHECK(limited > 0);
}

SCP_TEST(exceeding_the_constraint_bound_is_reported_rather_than_truncated) {
  const Timestamp evaluation = scp_test::base_instant();
  const std::vector<EvidenceRecord> nothing;

  // No publisher addresses any slot, so composition wants exactly one
  // incomplete-evidence constraint per evidence kind.
  scp::SitePolicy exact = scp_test::strict_policy();
  exact.max_constraints = scp::kEvidenceKindCount;
  const Result<SiteStateSnapshot> fits =
      scp::compose_site_state(nothing, options_for(evaluation, exact));
  SCP_REQUIRE_OK(fits);
  SCP_CHECK_EQ(fits.value().constraints.size(), scp::kEvidenceKindCount);
  SCP_CHECK_EQ(fits.value().slots.size(), scp::kEvidenceKindCount);

  scp::SitePolicy one_short = scp_test::strict_policy();
  one_short.max_constraints = scp::kEvidenceKindCount - 1;
  const Result<SiteStateSnapshot> overflowed =
      scp::compose_site_state(nothing, options_for(evaluation, one_short));
  SCP_REQUIRE_ERROR(overflowed, scp::StatusCode::LimitExceeded);

  scp::SitePolicy tiny = scp_test::strict_policy();
  tiny.max_constraints = 1;
  const Result<SiteStateSnapshot> truncated =
      scp::compose_site_state(nothing, options_for(evaluation, tiny));
  SCP_REQUIRE_ERROR(truncated, scp::StatusCode::LimitExceeded);
}

SCP_TEST(a_gate_that_is_open_does_not_close_when_readiness_only_improves) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();
  constexpr scp::GateKind kGates[] = {
      scp::GateKind::NewObligation,  scp::GateKind::MaintenanceEntry,
      scp::GateKind::ControlledDrain, scp::GateKind::EmergencyOperation,
      scp::GateKind::RecoveryStart,  scp::GateKind::ReturnToService};
  constexpr EvidenceKind kDomains[] = {EvidenceKind::PowerReadiness,
                                       EvidenceKind::CoolingReadiness,
                                       EvidenceKind::AsiCapability,
                                       EvidenceKind::DfiCapability};
  std::size_t pairs = 0;
  for (std::uint64_t scenario = 0; scenario < kScenarioCount; ++scenario) {
    const std::uint64_t seed = kMasterSeed * 17ULL + scenario * kSeedStride;
    SplitMix64 rng(seed);
    const std::vector<EvidenceRecord> records = random_evidence_set(rng, evaluation);
    const Result<SiteStateSnapshot> before =
        scp::compose_site_state(records, options_for(evaluation, policy));
    if (!before.has_value()) {
      continue;
    }
    const EvidenceKind domain = kDomains[scenario % 4];
    const scp::EvidenceSlot slot{scp::owner_of(domain), domain};
    const SlotResolution* previous = before.value().find_slot(slot);
    const std::uint64_t epoch =
        (previous == nullptr || previous->accepted_epoch.is_unset()) ? 1ULL
                                                                    : previous->accepted_epoch.value();
    const std::uint64_t generation =
        (previous == nullptr ? 0ULL : previous->accepted_generation.value()) + 1ULL;

    scp::Provenance provenance;
    provenance.authority = scp::owner_of(domain);
    provenance.instance = scp_test::instance_for(21);
    provenance.epoch = scp::Epoch(epoch);
    provenance.generation = scp::SourceGeneration(generation);
    provenance.sequence = scp::Sequence(1);
    provenance.issued_at = evaluation;
    Result<EvidenceRecord> upgraded = [&]() -> Result<EvidenceRecord> {
      if (domain == EvidenceKind::PowerReadiness || domain == EvidenceKind::CoolingReadiness) {
        scp::ReadinessEvidence body;
        body.snapshot = scp::SnapshotId(0xC0FFEE0000000009ULL, 0x0000000000000009ULL);
        body.readiness = scp::ReadinessLevel::Ready;
        body.headroom_milli_kw = 5000000;
        body.available_domains = 2;
        body.required_domains = 2;
        return EvidenceRecord::create(provenance, domain, body);
      }
      scp::CapabilityEvidence body;
      body.readiness = scp::ReadinessLevel::Ready;
      body.ready_domains = 8;
      body.total_domains = 8;
      body.ready_units = 512;
      return EvidenceRecord::create(provenance, domain, body);
    }();
    if (!upgraded.has_value()) {
      continue;
    }
    std::vector<EvidenceRecord> augmented = records;
    augmented.push_back(upgraded.value());
    const Result<SiteStateSnapshot> after =
        scp::compose_site_state(augmented, options_for(evaluation, policy));
    if (!after.has_value()) {
      check_scenario(false, "the improved evidence set composes",
                     "compose reported " + after.status().to_string(), seed, augmented);
      continue;
    }
    ++pairs;

    // The scope of the property: every other slot resolves to exactly what it
    // resolved to before, and observed readiness did not fall.
    bool other_slots_unchanged = true;
    for (const SlotResolution& resolution : before.value().slots) {
      if (resolution.slot == slot) {
        continue;
      }
      const SlotResolution* after_resolution = after.value().find_slot(resolution.slot);
      if (after_resolution == nullptr ||
          !(after_resolution->accepted_id == resolution.accepted_id) ||
          after_resolution->outcome != resolution.outcome) {
        other_slots_unchanged = false;
      }
    }
    check_scenario(other_slots_unchanged,
                   "upgrading one dependency domain leaves every other slot resolved the same",
                   "another slot changed", seed, augmented);
    check_scenario(after.value().readiness_percent >= before.value().readiness_percent,
                   "readiness never falls when a domain is upgraded to ready",
                   "before=" + std::to_string(before.value().readiness_percent) + " after=" +
                       std::to_string(after.value().readiness_percent),
                   seed, augmented);
    const SlotResolution* upgraded_slot = after.value().find_slot(slot);
    check_scenario(upgraded_slot != nullptr && upgraded_slot->accepted_id == upgraded.value().id,
                   "the upgraded publication is accepted for its slot",
                   "the upgrade was not accepted", seed, augmented);

    for (const scp::GateKind kind : kGates) {
      const Result<scp::ReadinessGate> before_gate =
          scp::evaluate_gate(kind, before.value(), policy);
      const Result<scp::ReadinessGate> after_gate = scp::evaluate_gate(kind, after.value(), policy);
      if (!before_gate.has_value() || !after_gate.has_value()) {
        check_scenario(false, "every gate evaluates on both snapshots",
                       std::string("gate ") + std::string(scp::to_string(kind)) + " failed to evaluate",
                       seed, augmented);
        continue;
      }
      const bool monotone = !before_gate.value().open || after_gate.value().open;
      check_scenario(monotone,
                     "no gate that was open becomes closed when readiness only improves",
                     std::string("gate ") + std::string(scp::to_string(kind)) +
                         " was open before and is closed after",
                     seed, augmented);
    }
  }
  SCP_CHECK(pairs > 100);
}

SCP_TEST(the_reported_reduction_buckets_account_for_every_record) {
  const Timestamp evaluation = scp_test::base_instant();
  const scp::SitePolicy policy = scp_test::strict_policy();

  // Two generations of a healthy site: 22 distinct identities, 11 of which lose.
  std::vector<EvidenceRecord> two_generations = scp_test::healthy_site_records(evaluation, 5);
  append(two_generations, scp_test::healthy_site_records(evaluation, 2));
  two_generations.push_back(two_generations.front());
  two_generations.push_back(two_generations.at(7));
  const Result<scp::ReductionResult> reduction =
      scp::reduce_evidence(two_generations, policy, evaluation);
  SCP_REQUIRE_OK(reduction);
  SCP_CHECK_EQ(reduction.value().duplicates_merged, std::size_t{2});
  SCP_CHECK_EQ(reduction.value().accepted.size(), scp::kEvidenceKindCount);
  check_reduction_partition(two_generations, reduction.value(), 101);

  // The same identity, with records the runtime refuses to accept at all.
  std::vector<EvidenceRecord> mixed = two_generations;
  const EvidenceRecord* facility = nullptr;
  for (const EvidenceRecord& record : two_generations) {
    if (record.kind == EvidenceKind::FacilityState) {
      facility = &record;
      break;
    }
  }
  SCP_REQUIRE(facility != nullptr);
  EvidenceRecord forged = *facility;
  forged.provenance.authority = SourceAuthority::FacilityCapacity;
  const Result<scp::EvidenceId> forged_id = scp::derive_evidence_id(
      forged.provenance, forged.kind, forged.schema_version, forged.body);
  SCP_REQUIRE_OK(forged_id);
  forged.id = forged_id.value();
  mixed.push_back(forged);

  EvidenceRecord identityless = *facility;
  identityless.id = scp::EvidenceId{};
  mixed.push_back(identityless);

  const Result<scp::ReductionResult> mixed_reduction = scp::reduce_evidence(mixed, policy,
                                                                           evaluation);
  SCP_REQUIRE_OK(mixed_reduction);
  SCP_CHECK_EQ(mixed_reduction.value().unauthorized_count, std::size_t{1});
  SCP_CHECK_EQ(distinct_rejected_count(mixed_reduction.value()), std::size_t{2});
  check_reduction_partition(mixed, mixed_reduction.value(), 102);
}

SCP_TEST_MAIN("scp.property-composition")
